<a href="https://colab.research.google.com/github/R12942159/DeepLearning/blob/main/2023ML_HW1_2nd_polynomial_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **2023 ML FALL HW1: PM2.5 Prediction (Regression)**

Author: MLTAs

Methods:
* Training with all data
* Training config: mini-batch=512, optimizer=Adam, learning rate=0.1 (TODO: Change the config!)



# **Import Some Packages**

In [1]:
import numpy as np
import csv
import math
import pandas as pd

In [2]:
import os
os.getcwd()

'/content'

# **Fix random seed**


This is for the reproduction of your result. **DO NOT modify this secton!**


In [3]:
## Edit: use np.random.seed(seed) (2022.10.12)
seed = 9487
np.random.seed(seed)

# **Download training data**


In [ ]:
!gdown --id "1Hfzrcm69QwdFvdeF0uASoQlcVxKw_hHy" --output "train.csv"

## Edit (2022.10.14) test.csv: 7th(WS_HR) and last column(pm2.5) is correctly switched.
!gdown --id '155N6fzI7vAFzHAGdy6jkaWIksWH6Y1G2' --output "test.csv"

# Incase the links above die, you can use the following instead.
#!gdown --id '11abE854Eyv4BA7qt5k8r_80sJ3KuOQUN' --output "train.csv"
#!gdown --id '1uod-Z4ztluXnuHtgUbm39nMudUKqXHMl' --output "test.csv"

# If the data is still missing, you can manually download it from kaggle, and upload the files under /content

In [5]:
def valid(x, y):
  # TODO: Try to filter out extreme values.
  #  ex: If PM2.5 > 100, then we don't use the data to train (return False), otherwise return True,

  return True


# Create your dataset
def parse2train(data, feats):

  x = []
  y = []

  # Use data #0~#7 to predict #8 => Total data length should be decresased by 8.
  total_length = data.shape[1] - 8

  for i in range(total_length):
    x_tmp = data[feats, i:i+8] # Use data #0~#7 to predict #8, data #1~#8 to predict #9, etc.
    y_tmp = data[-1, i+8] # last column of (i+8)th row: PM2.5

    # Filter out extreme values to train.
    if valid(x_tmp, y_tmp):
      x.append(x_tmp.reshape(-1,))
      y.append(y_tmp)

  # x.shape: (n, 15, 8)
  # y.shape: (n, 1)
  x = np.array(x)
  y = np.array(y)

  return x,y


#**Adam**
* This is our gradient descent algorithm. Adam was implemented.
* You can implement another algorithm such as SGD, which may (or may not) boost the performance.
* However, **modules like sklearn and pytorch are not allowed**.
* Ref: https://arxiv.org/pdf/1412.6980.pdf

![](https://i.imgur.com/jRaebdf.png)



In [39]:
index = np.arange(train_x.shape[0])
np.random.shuffle(index)
train_x = train_x[index]

In [39]:
# TODO: Implement 2-nd polynomial regression version for the report.
def minibatch(x, y, config):

    # Randomize the data in minibatch
    index = np.arange(x.shape[0])
    np.random.shuffle(index)
    x = x[index]
    y = y[index]

    # Initialization
    batch_size = config.batch_size
    lr = config.lr
    lam = config.lam
    epoch = config.epoch

    beta_1 = np.full(x[0].shape, 0.9).reshape(-1, 1)
    beta_2 = np.full(x[0].shape, 0.99).reshape(-1, 1)

    # Linear regression: only contains two parameters (w, b).
    # 2-nd polynomial regression(w1,w2,b)
    w1 = np.full(x[0].shape, 0.1).reshape(-1, 1)
    w2 = np.full(x[0].shape, 0.1).reshape(-1, 1)
    bias = 0.1

    m_t1 = np.full(x[0].shape, 0).reshape(-1, 1)
    m_t2 = np.full(x[0].shape, 0).reshape(-1, 1)
    m_t_3 = 0.0

    v_t1 = np.full(x[0].shape, 0).reshape(-1, 1)
    v_t2 = np.full(x[0].shape, 0).reshape(-1, 1)
    v_t_3 = 0.0

    t = 0
    epsilon = 1e-8

    # Training loop
    for num in range(epoch):
        for b in range(int(x.shape[0]/batch_size)):
            t+=1
            x_batch = x[b*batch_size:(b+1)*batch_size]
            y_batch = y[b*batch_size:(b+1)*batch_size].reshape(-1,1)

            # Prediction of linear regression
            # pred = np.dot(x_batch,w) + bias
            # pred = w1 * x_batch**2 + w2 * x_batch + bias
            pred = np.dot(x_batch**2, w1) + np.dot(x_batch, w2) + bias

            # loss
            loss = y_batch - pred

            # Compute gradient
            ## Edit: remove 2 * lam * np.sum(w)  (2022.10.11)
            # https://math.stackexchange.com/questions/1962877/compute-the-gradient-of-mean-square-error
            g_t1 = np.dot((x_batch**2).transpose(), loss) * (-2)
            g_t2 = np.dot(x_batch.transpose(),loss) * (-2)
            g_t_3 = loss.sum(axis=0) * (-2)

            m_t1 = beta_1*m_t1 + (1-beta_1)*g_t1
            m_t2 = beta_1*m_t2 + (1-beta_1)*g_t2
            m_t_3 = 0.9*m_t_3 + (1-0.9)*g_t_3

            v_t1 = beta_2*v_t1 + (1-beta_2)*np.multiply(g_t1, g_t1)
            v_t2 = beta_2*v_t2 + (1-beta_2)*np.multiply(g_t2, g_t2)
            v_t_3 = 0.99*v_t_3 + (1-0.99)*(g_t_3*g_t_3)

            m_cap1 = m_t1/(1-(beta_1**t))
            m_cap2 = m_t2/(1-(beta_1**t))
            m_cap_3 = m_t_3/(1-(0.9**t))

            v_cap1 = v_t1/(1-(beta_2**t))
            v_cap2 = v_t2/(1-(beta_2**t))
            v_cap_3 = v_t_3/(1-(0.99**t))

            w_1 = np.copy(w1)
            w_2 = np.copy(w2)

            # Update weight & bias
            w1 -= ((lr*m_cap1)/(np.sqrt(v_cap1)+epsilon))
            w2 -= ((lr*m_cap2)/(np.sqrt(v_cap2)+epsilon))
            bias -= (lr*m_cap_3)/(math.sqrt(v_cap_3)+epsilon)


    return w1, w2, bias

In [40]:
from argparse import Namespace

# TODO: Tune the config to boost your performance.
train_config = Namespace(
    batch_size = 512,
    lr = 1e-1,
    lam = 0.001,
    epoch = 1,
)


# **Training your regression model**

In [ ]:
data = pd.read_csv("/content/train.csv")
data

In [42]:
# Choose your features to train.
# Hint:
# 1. You can select more than one feature.
# 2. You should select "good" features.

# TODO: Carefully justify which feature should be chosen.
feats = [2]

In [43]:
# Training data preprocessing.

data = data.values
train_data = np.transpose(np.array(np.float64(data)))
train_x, train_y = parse2train(train_data, feats)

In [46]:
# Train your regression model

w1, w2, bias = minibatch(train_x, train_y, train_config)
print(w1.shape, w2.shape, bias.shape)

(8, 1) (8, 1) (1,)


In [47]:
w1, w2, bias

(array([[ 0.01593716],
        [-0.04401034],
        [ 0.10527231],
        [ 0.06896598],
        [-0.02042791],
        [-0.05631573],
        [ 0.03311423],
        [ 0.11240207]]),
 array([[0.24830965],
        [0.16806609],
        [0.24610574],
        [0.26935487],
        [0.21059001],
        [0.17554829],
        [0.21577532],
        [0.2831783 ]]),
 array([0.73146061]))

# **Testing:**


In [ ]:
def parse2test(data, feats):
  x = []
  for i in range(90):
    x_tmp = data[feats,8*i: 8*i+8]
    x.append(x_tmp.reshape(-1,))

  # x.shape: (n, 15, 8)
  x = np.array(x)
  return x


In [ ]:
data = pd.read_csv('test.csv')
print(data)
data = data.values

test_data = np.transpose(np.array(np.float64(data)))
test_x = parse2test(test_data, feats)

     AMB_TEMP    CO   NO   NO2   NOx    O3  PM10  WS_HR  RAINFALL    RH  SO2  \
0        27.5  0.22  0.7   9.0   9.8  13.2  31.0    1.2       0.0  79.0  1.7   
1        27.2  0.17  0.4   5.0   5.4  15.7  20.0    1.5       0.0  79.0  1.6   
2        26.8  0.17  0.4   4.3   4.8  12.8  16.0    1.6       0.0  81.0  1.3   
3        26.7  0.19  0.4   4.1   4.5  12.0  21.0    1.7       0.0  80.0  1.5   
4        26.4  0.22  0.4   4.1   4.6  10.1  23.0    2.2       0.0  81.0  1.5   
..        ...   ...  ...   ...   ...   ...   ...    ...       ...   ...  ...   
715      16.0  0.26  0.3   3.9   4.2  47.1  34.0    2.7       0.0  70.0  0.5   
716      15.6  0.25  0.4   3.3   3.7  44.1  27.0    3.0       0.0  74.0  0.6   
717      15.7  0.24  0.4   3.7   4.1  44.1  29.0    2.9       0.0  73.0  0.6   
718      15.1  0.24  0.6  10.5  11.1  29.9   9.0    0.8       0.0  95.0  0.6   
719      15.8  0.28  0.6   6.0   6.7  40.5  28.0    3.0       0.0  74.0  0.5   

     WD_HR  WIND_DIREC  WIND_SPEED  PM2

# **Write result as .csv**

---



In [ ]:
 with open('my_sol.csv', 'w', newline='') as csvf:
    # 建立 CSV 檔寫入器
    writer = csv.writer(csvf)
    writer.writerow(['Id','Predicted'])

    print(test_x.shape)
    for i in range(int(test_x.shape[0])):
      # Prediction of linear regression
      prediction = (np.dot(np.reshape(w,-1),test_x[i]) + bias)[0]
      writer.writerow([i, prediction] )

(90, 64)
